[[section-introduction-and-goals]]
== Introducción y metas

LoMap es una aplicación desarrollada por HappySw, en la que sus usuarios tendrán acceso a un mapa personalizado con los sitios de su interés dentro de la ciudad de Bruselas.

La funcionalidad principal se basa en un mapa, en el cual el propio usuario podrá seleccionar y guardar sus locales o lugares favoritos para tenerlos siempre a mano. Estos lugares pueden ir desde tiendas, bares o los monumentos más icónicos de la capital belga.

A diferencia de otras aplicaciones de mapas, LoMap permite al usuario que sea él el que decida que ver sobre su propio mapa, eliminando los lugares de menos interés, lo cual permite que sea muy práctico, tanto para los propios habitantes de la ciudad como para los turistas.

La aplicación respeta la privacidad de los clientes mediante los principios SOLID.


=== Descripción de los requisitos

Los principales requisitos funcionales de la aplicación serán:

* Los usuarios podrán marcar con chinchetas (temporal) los lugares de interés.
* El sistema almacenará y mostrará los lugares ya marcados anteriormente dependiendo de los datos que haya en el pod de cada usuario.
* Los usuarios podrán añadir tanto fotos, como comentarios en los lugares que hayan añadido.
* Los usuarios podrán agregar amigos para poder ver los lugares y comentarios que hicieron sobre los mismos.
* El mapa tendrá filtros, ya sea para filtrar los lugares por restaurantes o monumentos, o para ver los lugares favoritos de sus amigos.


=== Objetivos de calidad

[options="header",cols="1,2,2"]

|===
|Prioridad|Meta|Motivación
| 1 | Usabilidad | La aplicación debe ser fácilmente usable por cualquier usuario, con mucha o poca experiencia.
| 2 | Calidad | La aplicación debe satisfacer las necesidades del usuario de una forma correcta.
| 3 | Privacidad | El tratamiento de la información privada del usuario debe ser descentralizada, asegurando así su privacidad.
| 4 | Eficiencia | Al abrir la aplicación o seleccionar un elemento debe ser eficiente y sus tiempos de carga bajos.
|===

=== Stakeholders

[options="header",cols="1,2,2"]

|===
|Rol/Nombre|Contacto|Expectativas
| Cliente | Interaccionan de manera directa con la aplicación, tienen un usuario y amigos y pueden visualizar los puntos de interés | El objetivo principal es que sea capaz de interactuar con la aplicación de forma intuitiva y de una manera cómoda para el usuario aún sin ser un usuario avanzado.
| Equipo de desarrollo | Los creadores de la aplicación, pueden modificarla y mejorarla | Trabajan para aprender las tecnologías necesarias para desarrollar el proyecto y funcionar como un equipo.
| Profesores | Interaccionan con el equipo de desarrollo para corregir posibles defectos | Esperan que la aplicación sea funcional y cumpla los requisitos requeridos. También proporcionan soporte en caso de que sea necesario para el equipo de desarrollo.
|===
